library(reshape2)
activity_labels <- read.table("UCI HAR Dataset/activity_labels.txt")
activity_labels[,2] <- as.character(activity_labels[,2])
features <- read.table("UCI HAR Dataset/features.txt")
features[,2] <- as.character(features[,2])
features_mean <- grep(".*mean.*|.*std.*", features[,2])
features_mean.names <- features[features_mean,2]
features_mean.names = gsub('-mean', 'Mean', features_mean.names)
features_mean.names = gsub('-std', 'Std', features_mean.names)
features_mean.names <- gsub('[-()]', '', features_mean.names)
x_train <- read.table("UCI HAR Dataset/train/X_train.txt")[features_mean]
y_train <- read.table("UCI HAR Dataset/train/Y_train.txt")
subject_train <- read.table("UCI HAR Dataset/train/subject_train.txt")
train <- cbind(subject_train, y_train, x_train)
x_test <- read.table("UCI HAR Dataset/test/X_test.txt")[features_mean]
y_test <- read.table("UCI HAR Dataset/test/Y_test.txt")
subject_test <- read.table("UCI HAR Dataset/test/subject_test.txt")
test <- cbind(subject_test, y_test, x_test)
data_tidy <- rbind(train, test)
colnames(data_tidy) <- c("subject", "activity", features_mean.names)
data_tidy$activity <- factor(data_tidy$activity, levels = activity_labels[,1], labels = activity_labels[,2])
data_tidy$subject <- as.factor(data_tidy$subject)
data_tidy.melted <- melt(data_tidy, id = c("subject", "activity"))
data_tidy.mean <- dcast(data_tidy.melted, subject + activity ~ variable, mean)
write.table(data_tidy.mean, "data_tidy.txt", row.names = FALSE, quote = FALSE)